apiVersion: v1
entries:
  loki:
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.440368068Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 69e0857605523eee17a0127fb94daa420057a029fde9f5ac69ce89a59f8797a0
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.7.2.tgz
    version: 0.7.2
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.439806695Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: ec3eb0a7b46900195444e3dda3af8853e1cc5af88736ecb5484e517918468be0
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.7.1.tgz
    version: 0.7.1
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.439265234Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 7aaf0194556a224debd2ecb7572fa432c54ce1beff357d99dd6e55f772fe561f
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.7.0.tgz
    version: 0.7.0
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.438756485Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 485999e0808701bb5e890a75b056b97365e24e6953b88f8cac58d32497beea10
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.6.0.tgz
    version: 0.6.0
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.438162592Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 888563cc143746ae8216f5e96c11a3209f666b97d5dd9b7878b1f6b37dbb6db0
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.5.0.tgz
    version: 0.5.0
  loki-stack:
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.445496434Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 78ba73db65ae2b245260e1f690a84ed2e8c3a2cb53eee8f34ecabab2a7f1a1ee
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.7.2.tgz
    version: 0.7.2
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.444818171Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 279f7975c021f8ff073be73bb523a2243b0e8f88ec2138960557cd45f4418e1e
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.7.1.tgz
    version: 0.7.1
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.444170136Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 1b36c6c74eb760535cd7f8ae8896f6b9ee73fc6f7ae1bf54513636807af3171e
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.7.0.tgz
    version: 0.7.0
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.443550938Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: eb1114546434c0338ef7cc4d83e7feb9922b05735d16b2df981edb8ecfcd492d
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.6.2.tgz
    version: 0.6.2
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.442903458Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 8946fb38e6e4b6cb3fa91d49d878be981c1db08e8acb7b6638cfd88ac873747d
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.6.1.tgz
    version: 0.6.1
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.441631438Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 737c83e5833d36931afeec39b4f61b329c92cd8f1d43d5451bd1b7be4cff0826
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.6.0.tgz
    version: 0.6.0
  promtail:
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.446835841Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 1de15c38cc7b25722469a8c8573299d9392c8e07f02f65f0514e678db66a6d44
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.3.tgz
    version: 0.6.3
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.446480571Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 8461f3df3e011b95ef3d060a974a821441a0a503fc472c5ac425a340d0682ea5
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.2.tgz
    version: 0.6.2
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.446147582Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 639b884367892721200310029a54f6f63f1a7c08493174f0925604a37b03a182
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.1.tgz
    version: 0.6.1
  - appVersion: 0.0.1
    created: 2019-04-30T10:34:52.445818347Z
    description: Responsible for gathering logs and sending them to Loki
    digest: d8c072989461b9a6f416f5f37c408d616c1264f3109dc2f3301d310981b30894
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.0.tgz
    version: 0.6.0
generated: 2019-04-30T10:34:52.437281829Z
