apiVersion: v1
entries:
  loki:
  - appVersion: 0.0.1
    created: 2019-04-09T07:17:34.409143941Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: d176fbc384c90282b47b7e91413ed25528b521f6828e632ed5744f58780a9d04
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.5.0.tgz
    version: 0.5.0
generated: 2019-04-09T07:17:34.408408422Z
