apiVersion: v1
entries:
  loki:
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.675360786Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 096ad9077373e1f2be65e4a99a2e917a048c16eb32e9d7607c04a9629a3bdaf9
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.9.0.tgz
    version: 0.9.0
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.675031663Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 47405b00f7c0fa7317b42a3a4d54187449c32713823c7e69103aa535acedc7ad
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.8.5.tgz
    version: 0.8.5
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.674687209Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: c2db1b9385b3eedab947350e7f05a0d1ff55926b8e9eee9eea08e92f823fe8f9
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.8.4.tgz
    version: 0.8.4
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.674356303Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 324ce9ebb8c3148d440bd8216760e558ed4b63309e759f7ae65493ef897d6df1
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.8.3.tgz
    version: 0.8.3
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.674018423Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 1a9c09b6e49fc7ab0deddf0ee2210f4c91c3cc40ae66d090d0ca4d5998a2c2cc
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.8.2.tgz
    version: 0.8.2
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.673658487Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: e716194272835e3c069d5232a70924390568fa589a1a05fab03e9cfbee8730b3
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.8.1.tgz
    version: 0.8.1
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.672461423Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 1b4a6c327668e312d6b61626c3bd48eaa5139e60804d06afebc6a351cba97ff3
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.8.0.tgz
    version: 0.8.0
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.671903803Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 007b886263b9f7c004960c5477558d7d0f7567e8b4805191281e81b3e0a87343
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.7.2.tgz
    version: 0.7.2
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.671353448Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: ec3eb0a7b46900195444e3dda3af8853e1cc5af88736ecb5484e517918468be0
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.7.1.tgz
    version: 0.7.1
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.670789392Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 7aaf0194556a224debd2ecb7572fa432c54ce1beff357d99dd6e55f772fe561f
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.7.0.tgz
    version: 0.7.0
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.670234544Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 485999e0808701bb5e890a75b056b97365e24e6953b88f8cac58d32497beea10
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.6.0.tgz
    version: 0.6.0
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.66968638Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 888563cc143746ae8216f5e96c11a3209f666b97d5dd9b7878b1f6b37dbb6db0
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.5.0.tgz
    version: 0.5.0
  loki-stack:
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.677883146Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: c51e78bae2aa41cc789cbae11dc96e95d2211143e83e71fda37c7d2b58450a73
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.10.0.tgz
    version: 0.10.0
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.693080267Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 57391df764929a66c229a47c2a1b979b721908df4e30fec098dbf8b74fd32e58
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.9.5.tgz
    version: 0.9.5
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.689878983Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 5421a8b30e5b553fdee98e7ec0c14d36a07c7ec9f163c3d0c0e2b46ddeb26645
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.9.4.tgz
    version: 0.9.4
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.687331854Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: f65ef4b0d447183027b93393e5af2b9c487e1021179c33bf267cb91323dc2ce9
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.9.3.tgz
    version: 0.9.3
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.68667544Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 9cee5fd38d60cd3bbc5642db26923cd5bde4d20a93eb1cf5146dff7dcfb05880
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.9.2.tgz
    version: 0.9.2
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.685990781Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 8fc04b7ec127f31a654df1f9d8aee67aa4fcb91c1723e413d5e645eb08ecd788
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.9.1.tgz
    version: 0.9.1
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.685284668Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: f9c9a361174b4eaa97a38ffd60694649060fac698584ba07530c8714eb7c15a2
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.9.0.tgz
    version: 0.9.0
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.684615458Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 1dfec1dd8fe35147eb14af8cdd0a17d23be1b132ab733aa9944660f33994c7db
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.8.1.tgz
    version: 0.8.1
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.683936193Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 0a98ad11b5eb6568fc60706ae27decb7ad67382c62b0d0ab9cee7f16ac41f682
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.8.0.tgz
    version: 0.8.0
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.683115651Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 592eee838821d94146a76e8b22aafa5a05a7d4e9664463cc3599164c1f7fd261
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.7.2.tgz
    version: 0.7.2
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.681479342Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 279f7975c021f8ff073be73bb523a2243b0e8f88ec2138960557cd45f4418e1e
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.7.1.tgz
    version: 0.7.1
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.680746701Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 1b36c6c74eb760535cd7f8ae8896f6b9ee73fc6f7ae1bf54513636807af3171e
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.7.0.tgz
    version: 0.7.0
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.68004425Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: eb1114546434c0338ef7cc4d83e7feb9922b05735d16b2df981edb8ecfcd492d
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.6.2.tgz
    version: 0.6.2
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.679338549Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 8946fb38e6e4b6cb3fa91d49d878be981c1db08e8acb7b6638cfd88ac873747d
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.6.1.tgz
    version: 0.6.1
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.678608836Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 737c83e5833d36931afeec39b4f61b329c92cd8f1d43d5451bd1b7be4cff0826
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.6.0.tgz
    version: 0.6.0
  promtail:
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.695670937Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 6c149cbafc8ee05d90838a38f8ef37fd7d0c0c6f0805a6f270706ea3005df792
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.7.3.tgz
    version: 0.7.3
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.695350497Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 593f579c023c1df962196914e8204df6516dc7482c49b53a8d2c75e27977141d
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.7.2.tgz
    version: 0.7.2
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.695029953Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 728037bd94c46bc21309aa259c8531aa53f216400e8f42c40aa0755890065be2
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.7.1.tgz
    version: 0.7.1
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.694702438Z
    description: Responsible for gathering logs and sending them to Loki
    digest: af2dca916bb95b909646de6710a82c5ad6714b410ee97ce0b4ccb0455320d507
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.7.0.tgz
    version: 0.7.0
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.694386445Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 61ec9fb6727069ddfe37657db06a22163de31c5deb27aeb5333e7c5fdf34aa2d
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.3.tgz
    version: 0.6.3
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.694063262Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 8461f3df3e011b95ef3d060a974a821441a0a503fc472c5ac425a340d0682ea5
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.2.tgz
    version: 0.6.2
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.693748491Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 639b884367892721200310029a54f6f63f1a7c08493174f0925604a37b03a182
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.1.tgz
    version: 0.6.1
  - appVersion: 0.0.1
    created: 2019-05-30T06:07:46.693429041Z
    description: Responsible for gathering logs and sending them to Loki
    digest: d8c072989461b9a6f416f5f37c408d616c1264f3109dc2f3301d310981b30894
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.0.tgz
    version: 0.6.0
generated: 2019-05-30T06:07:46.668707956Z
