apiVersion: v1
entries:
  loki:
  - appVersion: 0.0.1
    created: 2019-04-12T10:11:47.752699145Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: cc85d859a65f4d7d2e0ea9bf6fd30f34240a56c2936788729301c320fcde1a43
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.6.0.tgz
    version: 0.6.0
  - appVersion: 0.0.1
    created: 2019-04-12T10:11:47.752142387Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 888563cc143746ae8216f5e96c11a3209f666b97d5dd9b7878b1f6b37dbb6db0
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.5.0.tgz
    version: 0.5.0
  loki-stack:
  - appVersion: 0.0.1
    created: 2019-04-12T10:11:47.755942366Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: b5b8d3d500d46c710d5439a54601861fce65512e0404f3f01f0991b5a843df29
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.6.2.tgz
    version: 0.6.2
  - appVersion: 0.0.1
    created: 2019-04-12T10:11:47.754902073Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 8946fb38e6e4b6cb3fa91d49d878be981c1db08e8acb7b6638cfd88ac873747d
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.6.1.tgz
    version: 0.6.1
  - appVersion: 0.0.1
    created: 2019-04-12T10:11:47.753775568Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 737c83e5833d36931afeec39b4f61b329c92cd8f1d43d5451bd1b7be4cff0826
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.6.0.tgz
    version: 0.6.0
  promtail:
  - appVersion: 0.0.1
    created: 2019-04-12T10:11:47.75833259Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 39aecb5177d329d0e096a34521ec319f0d6e1e565b5c3328bd63488f7e68ab5b
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.2.tgz
    version: 0.6.2
  - appVersion: 0.0.1
    created: 2019-04-12T10:11:47.757035887Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 639b884367892721200310029a54f6f63f1a7c08493174f0925604a37b03a182
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.1.tgz
    version: 0.6.1
  - appVersion: 0.0.1
    created: 2019-04-12T10:11:47.756495173Z
    description: Responsible for gathering logs and sending them to Loki
    digest: d8c072989461b9a6f416f5f37c408d616c1264f3109dc2f3301d310981b30894
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.0.tgz
    version: 0.6.0
generated: 2019-04-12T10:11:47.751217004Z
