server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: cri-logs-test
  pipeline_stages:
    - match:
        stages:
          - cri: {}
  static_configs:
  - targets:
      - localhost
    labels:
      job: cri-logs
      __path__: /Users/kaviraj/.logs/cri.log
      pipeline_stages:
        - match:
            stages:
              - cri: {}
